# Deployment for Admin UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-admin-app
  template:
    metadata:
      labels:
        app: nginx-admin-app
    spec:
      containers:
        - name: nginx-admin-app
          image: skillhub.azurecr.io/nginx-admin-app:latest
          ports:
            - containerPort: 8080
---
# Service for Admin UI
apiVersion: v1
kind: Service
metadata:
  name: nginx-admin-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nginx-admin-app
  type: LoadBalancer
